### ISSUE TITLE
Fancy neural to-do list

### ISSUE THREAD

**Issue by konstantinosKokos** [konstantinosKokos/LassyPreprocessing#4]
- [ ] character embeddings for morphology
- [ ] context-dependence using attention / recurrency
- [ ] find some evaluation metric
- [ ] evaluate when using less types
- [ ] sci-fi: try using dynamic recurrence for arguments
